import { Link } from "react-router-dom";
import { motion } from "framer-motion";

const faq = [
  {
    q: "What is FullTime and why does it exist?",
    a: "FullTime is a trustless, on-chain prediction market protocol built on Solana for the FIFA World Cup 2026. It was built for the TxODDS x Solana x Superteam Earn Hackathon (Prediction Markets & Settlement track, $18,000 prize pool). Unlike centralized platforms like Polymarket or Augur v1 where a human operator clicks 'resolve', FullTime eliminates trust entirely: settlement outcomes are verified cryptographically via Merkle proofs generated by TxLINE (TxODDS' oracle network) and executed on-chain through a Cross-Program Invocation (CPI). The architecture is designed so that no single party — not the market creator, not the developer, not a DAO — can tamper with the result. Either the proof checks out, or the transaction reverts. Period.",
  },
  {
    q: "How does the trustless settlement work technically?",
    a: "When a match ends, the TxLINE oracle network produces a Merkle tree containing all verified match statistics (goals, cards, corners, etc.) for that day. Our off-chain relay service listens to SSE (Server-Sent Events) from TxLINE, detects phase changes, fetches the Merkle proofs for the relevant fixture, and submits a settle_market transaction to the FullTime program. The smart contract then performs a CPI call to the TxLINE Txoracle program on Solana devnet, executing the validate_stat instruction which verifies: (1) the proof path from the stat to the fixture's event sub-tree root, (2) the proof path from the fixture root to the daily Merkle root, (3) the daily_scores_roots PDA is authentic. If all three checks pass, the contract derives the winner mathematically (home_goals > away_goals → YES). The entire settlement flow takes under 1 second from final whistle to on-chain confirmation. This is genuine cryptographic verification — not a trusted oracle push.",
  },
  {
    q: "What is the market structure? YES/NO only?",
    a: "FullTime v2 supports binary YES/NO markets exclusively. Each market has two pools (pool_yes, pool_no), a 2% protocol fee (200 bps), and two settlement modes: (a) Trustless — the market references a TxLINE fixture_id, and settlement is performed via CPI Merkle proof verification when the match concludes; (b) Manual — the market creator calls resolve_market(outcome) for general questions that aren't tied to match data (e.g., tournament champion, top scorer, MVP predictions). Both modes result in the same pool distribution and claim flow. The question field is free-text (up to 200 characters), enabling any prediction type: match winners, over/under goals, individual player stats, tournament outcomes, and beyond.",
  },
  {
    q: "How are payouts calculated?",
    a: "FullTime uses a parimutuel payout model. When a market is settled, the losing pool is distributed proportionally to winners. The formula: gross_payout = user_bet_amount × total_pool / winning_pool. Then a 2% fee (fee_bps = 200) is deducted: net_payout = gross_payout - (gross_payout × 200 / 10000). The fee goes to the market creator as a protocol incentive. All arithmetic uses anchor_lang's checked_add/sub/mul/div to prevent overflow vulnerabilities — a non-negotiable security standard in Solana program development. If you bet on the winning side, you always get back at least your principal plus a share of the losers' pool.",
  },
  {
    q: "What wallets are supported and which network?",
    a: "FullTime runs on Solana Devnet. The frontend integrates @solana/wallet-adapter-react with Phantom wallet support out of the box. Users must switch their Phantom wallet to Devnet mode (Settings → Developer Settings → Testnet Mode → Devnet). The Anchor program is deployed at 58a2h7zogfV5ZgUsfyr1DZ36j1bgcwfCkGvd8fwppy5x. All accounts (markets, bets) are Program Derived Addresses (PDAs) with deterministic seeds: market PDA = ['market', program_id, creator_pubkey, fixture_id_le_bytes], bet PDA = ['bet', market_pubkey, bettor_pubkey]. This means your market and bet addresses are computable off-chain before transaction submission, a critical optimization for UX responsiveness.",
  },
  {
    q: "How do I get test SOL to use the dApp?",
    a: "Visit the Faucet page (/faucet) built into the dApp. Connect your Phantom wallet (Devnet) and click 'Request 1 SOL'. This calls the Solana JSON-RPC requestAirdrop method with a 1 SOL cap per request. If rate-limited by the public RPC, you can also use the official faucet at faucet.solana.com or run solana airdrop 1 <YOUR_ADDRESS> --url devnet from the Solana CLI. The program wallet 52rWpvP4SeQ2n8B3ULPsYN6zTmYd6ZeQHM8VqXfjcsZ8 currently holds ~12.5 SOL for testing.",
  },
  {
    q: "What are the smart contract's security measures?",
    a: "Security is the foundation of FullTime. Key measures include: (1) All arithmetic uses checked_add/sub/mul/div to prevent integer overflow/underflow — there is no unchecked math anywhere in the codebase. (2) Market status lifecycle is strictly enforced: every instruction validates the current status before executing (Pending→Open→Closed→Settled/Cancelled), with no bypass possible. (3) Creator-only constraints on cancel_market and resolve_market use Anchor's constraint = market.creator == creator.key(). (4) The settle_market instruction verifies the daily_scores_merkle_roots PDA against the known TxLINE program ID using find_program_address — fake PDA accounts cannot pass this check. (5) The CPI to validate_stat has a fixed 8-byte discriminator matching the Txoracle IDL v1.4.2 — the wrong discriminator causes immediate revert. (6) The program is deployed via BPFLoaderUpgradeab1e11111111111111111111111, the standard Solana program loader. (7) 15 comprehensive unit tests cover all happy paths and error cases (create, open, bet, close, settle status checks, cancel, refund, claim, PDA determinism).",
  },
  {
    q: "What is the relay service and how does SSE work?",
    a: "The relay service (relay-service/src/) is a Node.js backend that bridges TxLINE's real-time data feed with the Solana blockchain. Architecture: (1) scores-stream.ts opens an SSE connection to TxLINE and listens for phase change events — phase 5/10/13 triggers settlement, phase 15/16 triggers cancellation detection. Uses AbortController for clean teardown and exponential backoff for reconnection. (2) proof-fetcher.ts makes 2 API calls to fetch Merkle proofs (statKey=1 for home goals, statKey=2 for away goals), receiving raw byte arrays (no base64 conversion needed). (3) settlement-submitter.ts builds and submits the settle_market transaction with a 1.4M CU ComputeBudget to handle the CPI verification. (4) index.ts orchestrates everything: SSE listener + 60-second polling fallback + market registry sync. The relay service operates permissionlessly — anyone can run it.",
  },
  {
    q: "Can I cancel a market or refund my bet?",
    a: "Yes. The market creator can call cancel_market at any time while the market is in Pending, Open, or Closed status (not Settled). Once cancelled, any bettor who placed a bet on that market can call refund_bet to reclaim their SOL. The refund instruction: (a) verifies the market is Cancelled, (b) deducts the bet amount from the appropriate pool (pool_yes or pool_no), (c) transfers SOL from the market PDA back to the bettor, (d) auto-closes the bet account via Anchor's close = bettor constraint, reclaiming the rent-exempt lamports. This is a full round-trip: create → bet → cancel → refund → account closed. No funds are ever permanently locked.",
  },
  {
    q: "How does FullTime compare to Polymarket, Augur, and other prediction markets?",
    a: "Polymarket runs on Polygon and relies on UMA's Optimistic Oracle — a human dispute resolution system where outcomes can be challenged and voted on, but ultimately a trusted party declares the result. Augur v2 uses a similar dispute-based resolution with REP token holders. FullTime eliminates the human element entirely: settlement is mathematical, not social. The TxLINE Merkle proof is verified on-chain through a cryptographic CPI — either the proof validates or it doesn't. There is no dispute window, no challenge period, no voting mechanism needed for the core match-result markets. Additionally, FullTime's SSE-based relay achieves sub-1-second settlement latency from final whistle to on-chain confirmation, compared to minutes or hours on dispute-based systems. For manual markets (non-match questions), the creator resolves directly — a pragmatic trade-off that expands the universe of possible prediction types while keeping the core differentiator intact.",
  },
  {
    q: "Where can I verify the on-chain data independently?",
    a: "Everything is verifiable on Solscan (solscan.io, cluster=devnet). Key addresses: Program ID 58a2h7zogfV5ZgUsfyr1DZ36j1bgcwfCkGvd8fwppy5x, TxLINE Txoracle 6pW64gN1s2uqjHkn1unFeEjAwJkPGHoppGvS715wyP2J. Every market PDA is deterministically derived, every bet PDA is deterministically derived, and every settle_market transaction permanently records the daily_scores_merkle_roots PDA used for verification. The full IDL is at frontend/public/idl.json in the GitHub repo (github.com/yt2025id-lab/fulltime, public). The source code is fully open-source under the programs/fulltime/src/lib.rs directory — approximately 900 lines of Rust with comprehensive inline comments.",
  },
  {
    q: "What's the tech stack and why these choices?",
    a: "Smart Contract: Anchor framework v0.30.1 + Rust, deployed via BPFLoaderUpgradeable on Solana Devnet. Anchor was chosen for its derive macros (Accounts, program), automatic IDL generation enabling type-safe frontend integration, and battle-tested security patterns. Frontend: React 19 + Vite 8 + TypeScript + Tailwind CSS v4, with @solana/wallet-adapter-react for Phantom wallet integration and @coral-xyz/anchor for program interaction. The IDL is loaded at runtime via fetch('/idl.json'), enabling the frontend to work with any deploy without recompilation. Framer Motion provides the animated BlurText, scroll reveals, and button interactions. Relay Service: Node.js + TypeScript, with SSE (EventSource) for real-time TxLINE data, AbortController for clean resource management, and @solana/web3.js for transaction submission. The entire stack runs on a single Vercel deployment (fulltime-wc.vercel.app) with SPA rewrites for React Router.",
  },
];

const fadeIn = {
  initial: { filter: "blur(8px)", opacity: 0, y: 20 },
  animate: { filter: "blur(0px)", opacity: 1, y: 0 },
};

export default function Faq() {
  return (
    <div className="min-h-screen bg-black relative">
      <div className="fixed inset-0 z-0 bg-cover bg-center" style={{ backgroundImage: "url(https://images.unsplash.com/photo-1551958219-acbc608c6377?w=1920&q=80)" }}>
        <div className="absolute inset-0 bg-black/85 backdrop-blur-[2px]" />
      </div>

      <nav className="sticky top-0 z-40 border-b border-red-800/30 bg-[#c0392b]/95 backdrop-blur-lg">
        <div className="max-w-7xl mx-auto grid grid-cols-3 items-center px-4 sm:px-6 py-3">
          <div className="flex items-center gap-4">
            <Link to="/app" className="text-sm text-white/70 hover:text-white font-mono transition-colors">&larr; Back</Link>
            <span className="text-lg">⚽</span>
            <span className="font-mono font-bold text-white text-lg">Full<span className="text-white/40">Time</span></span>
          </div>
          <div className="flex items-center justify-center gap-2">
            <Link to="/app" className="rounded-full px-4 py-1.5 text-sm font-mono text-white/50 hover:text-white transition-colors">Markets</Link>
            <Link to="/matches" className="rounded-full px-4 py-1.5 text-sm font-mono text-white/50 hover:text-white transition-colors">Matches</Link>
            <Link to="/faq" className="bg-white/15 rounded-full px-4 py-1.5 text-sm font-mono text-white font-medium">FAQ</Link>
          </div>
          <div />
        </div>
      </nav>

      <div className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 py-12">
        <motion.div {...fadeIn} transition={{ duration: 0.6 }}>
          <p className="text-sm font-mono text-red-300/60 mb-4">// FAQ</p>
          <h1 className="font-mono font-bold text-white text-5xl md:text-6xl tracking-[-2px] mb-4">
            Frequently Asked <span className="text-red-300/60">Questions</span>
          </h1>
          <p className="font-mono text-sm text-white/40 mb-12 max-w-2xl">
            Everything you need to know about FullTime — the trustless prediction market protocol for World Cup 2026 on Solana.
          </p>
        </motion.div>

        <div className="space-y-4">
          {faq.map((item, i) => (
            <motion.div
              key={i}
              initial={{ filter: "blur(5px)", opacity: 0, y: 20 }}
              whileInView={{ filter: "blur(0px)", opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.06 }}
              className="bg-white/[0.03] backdrop-blur-sm border border-white/[0.08] rounded-2xl p-6 hover:border-white/15 transition-colors"
            >
              <h3 className="font-mono font-bold text-white text-base mb-3">{item.q}</h3>
              <p className="font-mono text-sm text-white/50 leading-relaxed">{item.a}</p>
            </motion.div>
          ))}
        </div>

        <div className="mt-16 text-center">
          <p className="font-mono text-xs text-white/20">
            Built for TxODDS x Solana x Superteam Earn Hackathon · Prediction Markets & Settlement · July 2026
          </p>
        </div>
      </div>
    </div>
  );
}
