import { useState } from "react";
import { Link } from "react-router-dom";
import { useWallet } from "@solana/wallet-adapter-react";
import { WalletModalButton, WalletDisconnectButton } from "@solana/wallet-adapter-react-ui";
import { motion } from "framer-motion";
import { useLang } from "../lib/i18n/context";
import LangToggle from "../components/LangToggle";

const faqEN = [
  {
    q: "What is FullTime?",
    a: "FullTime is a trustless, on-chain prediction market protocol built on Solana for FIFA World Cup 2026. Developed for the TxODDS × Solana × Superteam Earn Hackathon ($18,000 prize pool, Prediction Markets & Settlement track). Unlike centralized platforms where a human operator clicks 'resolve', FullTime eliminates trust entirely: settlement outcomes are verified cryptographically via Merkle proofs generated by TxLINE (TxODDS' oracle network) and executed on-chain through Cross-Program Invocation (CPI). Either the proof checks out, or the transaction reverts. No middleman, no admin key, no dispute window.",
  },
  {
    q: "How does trustless settlement work?",
    a: "When a match concludes, TxLINE produces a cryptographic Merkle tree containing all verified match statistics for that day. The relay service detects this via SSE (Server-Sent Events), fetches Merkle proofs from /api/scores/stat-validation, and submits a settle_market transaction. The on-chain program performs CPI into TxLINE's validate_stat instruction which verifies: (1) the stat→fixture Merkle proof path, (2) the fixture→daily root proof path, (3) the daily_scores_roots PDA is authentic. If all three checks pass, the winner is derived: home_goals > away_goals → YES, otherwise → NO. From final whistle to on-chain confirmation: under 1 second.",
  },
  {
    q: "How does YES/NO and payout math work?",
    a: "FullTime uses binary YES/NO markets with parimutuel pooling. All bets on the losing side are distributed proportionally to winners. Payout formula: gross = your_bet × (total_pool / winning_pool). Protocol fee is 200 bps (2%), calculated as fee = gross × 200 / 10000. Net payout = gross - fee. If you bet 0.1 SOL on YES with a 0.3 SOL winning pool and 0.5 SOL total pool, you receive approximately 0.163 SOL — your stake plus your share of the NO pool. All arithmetic uses Anchor's checked_add/sub/mul/div to prevent overflow vulnerabilities.",
  },
  {
    q: "What are the two market types?",
    a: "Trustless Markets (isTrustless=true): tied to TxLINE fixture IDs, auto-settled via Merkle proof CPI when the match ends, no human intervention needed. Manual Markets (isTrustless=false): created for any YES/NO question, the market creator calls resolve_market(outcome) to settle. Both share the same pool structure (pool_yes/pool_no), bet interface, and claim flow. Trustless markets use fixture_id from TxLINE; manual markets use fixture_id=0.",
  },
  {
    q: "What wallets are supported? How do I set up?",
    a: "FullTime runs on Solana Devnet. Supported wallets: Phantom, Solflare, and Torus (social login). To set up: (1) Install Phantom browser extension, (2) Open Phantom → Settings → Developer Settings → Testnet Mode → select Devnet, (3) Get free SOL from the /faucet page or faucet.solana.com (GitHub login required), (4) Connect on /app. The Anchor program is deployed at 58a2h7zogfV5ZgUsfyr1DZ36j1bgcwfCkGvd8fwppy5x on devnet.",
  },
  {
    q: "How do I get test SOL?",
    a: "Visit the built-in Faucet page (/faucet). Connect your Phantom wallet (Devnet) and click 'Request 1 SOL'. This calls the Solana JSON-RPC requestAirdrop method. If rate-limited, use faucet.solana.com directly — sign in with GitHub, paste your wallet address, complete captcha, and claim up to 5 SOL per request. Devnet SOL has no real monetary value.",
  },
  {
    q: "What security measures protect the smart contract?",
    a: "Seven layers of security: (1) All arithmetic uses checked_add/sub/mul/div — zero unchecked math. (2) Market status lifecycle is strictly enforced (Pending→Open→Closed→Settled/Cancelled), every instruction validates current state. (3) Creator-only constraints via Anchor's constraint = market.creator == creator.key(). (4) settle_market verifies daily_scores_merkle_roots PDA against known TxLINE program ID via findProgramAddressSync. (5) CPI to validate_stat uses a fixed 8-byte discriminator matching Txoracle IDL v1.4.2. (6) Deployed via BPFLoaderUpgradeable, Solana's standard program loader. (7) 15 comprehensive unit tests covering all happy paths and error cases.",
  },
  {
    q: "Can I cancel a market or get a refund?",
    a: "Yes. Market creator can call cancelMarket at any time while status is Pending, Open, or Closed (not Settled). Bettors then call refundBet which: (a) verifies market is Cancelled, (b) deducts bet amount from the corresponding pool (pool_yes or pool_no), (c) transfers SOL from the market PDA back to the bettor, (d) auto-closes the bet account via Anchor's close=bettor constraint, reclaiming rent-exempt lamports. No funds are permanently locked.",
  },
  {
    q: "How is FullTime different from Polymarket or Augur?",
    a: "Polymarket runs on Polygon and relies on UMA's Optimistic Oracle — a human dispute resolution system where outcomes are voted on. Augur v2 uses a similar dispute-based model with REP token holders. FullTime's core differentiator: settlement is purely mathematical. The TxLINE Merkle proof is verified on-chain via CPI — either it validates or it doesn't. No dispute window, no challenge period, no voting. Additionally, SSE-based relay achieves sub-1-second settlement latency versus minutes or hours on dispute-based systems. For manual markets, the creator resolves directly — a trade-off that expands the universe of possible predictions while keeping the trustless core intact.",
  },
  {
    q: "How do I verify everything on-chain?",
    a: "All addresses are verifiable on Solscan (devnet). Key addresses: Program ID 58a2h7zogfV5ZgUsfyr1DZ36j1bgcwfCkGvd8fwppy5x, TxLINE Txoracle 6pW64gN1s2uqjHkn1unFeEjAwJkPGHoppGvS715wyP2J. Every market PDA is deterministically derived from seeds [b'market', program_id, creator_pubkey, fixture_id_le]. Every bet PDA from [b'bet', market_pubkey, bettor_pubkey]. Every settle_market transaction permanently records the daily_scores_merkle_roots PDA. Full source code at github.com/yt2025id-lab/fulltime (public).",
  },
  {
    q: "What is the relay service and SSE architecture?",
    a: "The relay service (relay-service/src/) bridges TxLINE's real-time feed with Solana. Architecture: (1) scores-stream.ts connects to TxLINE SSE, detects phase changes (5/10/13=settle, 15/16=cancel) using AbortController for clean teardown and exponential backoff. (2) proof-fetcher.ts fetches Merkle proofs via 2 API calls (statKey=1 home, statKey=2 away). (3) settlement-submitter.ts builds transactions with 1.4M CU ComputeBudget for CPI verification. (4) index.ts orchestrates SSE + 60s polling fallback + market registry sync. The relay operates permissionlessly — anyone can run it.",
  },
  {
    q: "What's the tech stack and why these choices?",
    a: "Smart Contract: Anchor v0.30.1 + Rust, deployed via BPFLoaderUpgradeable on Solana Devnet. Anchor chosen for derive macros (Accounts, program), automatic IDL generation, and battle-tested patterns. Frontend: React 19 + Vite 8 + TypeScript + Tailwind CSS v4, with @solana/wallet-adapter-react (Phantom/Solflare/Torus) and @coral-xyz/anchor. IDL loaded at runtime via fetch('/idl.json'). Framer Motion for animations. Relay Service: Node.js + TypeScript, SSE for real-time TxLINE data, @solana/web3.js for transaction submission. Vercel for hosting (fulltime-wc.vercel.app). football-data.org API for live scores, standings, and knockout data.",
  },
];

const faqID: typeof faqEN = [
  {
    q: "Apa itu FullTime?",
    a: "FullTime adalah protokol pasar prediksi on-chain tanpa kepercayaan yang dibangun di Solana untuk Piala Dunia FIFA 2026. Dikembangkan untuk TxODDS × Solana × Superteam Earn Hackathon ($18.000 hadiah, trek Prediction Markets & Settlement). Tidak seperti platform terpusat di mana operator manusia mengklik 'resolve', FullTime menghilangkan kepercayaan sepenuhnya: hasil penyelesaian diverifikasi secara kriptografis melalui Merkle proof yang dihasilkan oleh TxLINE (jaringan oracle TxODDS) dan dieksekusi on-chain melalui Cross-Program Invocation (CPI). Bukti cocok, atau transaksi dibatalkan. Tanpa perantara, tanpa kunci admin, tanpa jendela sengketa.",
  },
  {
    q: "Bagaimana cara kerja penyelesaian tanpa kepercayaan?",
    a: "Saat pertandingan selesai, TxLINE menghasilkan pohon Merkle kriptografis yang berisi semua statistik pertandingan terverifikasi untuk hari itu. Relay service mendeteksi ini melalui SSE (Server-Sent Events), mengambil Merkle proof dari /api/scores/stat-validation, dan mengirim transaksi settle_market. Program on-chain melakukan CPI ke instruksi validate_stat TxLINE yang memverifikasi: (1) jalur Merkle proof stat→fixture, (2) jalur proof fixture→daily root, (3) PDA daily_scores_roots adalah asli. Jika ketiga pemeriksaan lolos, pemenang ditentukan: home_goals > away_goals → YES, sebaliknya → NO. Dari peluit akhir hingga konfirmasi on-chain: di bawah 1 detik.",
  },
  {
    q: "Bagaimana matematika YES/NO dan pembayaran?",
    a: "FullTime menggunakan pasar biner YES/NO dengan pengumpulan parimutuel. Semua taruhan di sisi yang kalah didistribusikan secara proporsional kepada pemenang. Rumus pembayaran: bruto = taruhan_anda × (total_pool / winning_pool). Biaya protokol adalah 200 bps (2%), dihitung sebagai fee = bruto × 200 / 10000. Pembayaran bersih = bruto - fee. Jika Anda bertaruh 0.1 SOL di YES dengan winning pool 0.3 SOL dan total pool 0.5 SOL, Anda menerima sekitar 0.163 SOL — taruhan Anda ditambah bagian dari pool NO. Semua aritmatika menggunakan checked_add/sub/mul/div Anchor untuk mencegah kerentanan overflow.",
  },
  {
    q: "Apa dua jenis pasar yang ada?",
    a: "Pasar Trustless (isTrustless=true): terikat pada ID fixture TxLINE, diselesaikan otomatis via Merkle proof CPI saat pertandingan berakhir, tanpa intervensi manusia. Pasar Manual (isTrustless=false): dibuat untuk pertanyaan YES/NO apa pun, pembuat pasar memanggil resolve_market(outcome) untuk menyelesaikan. Keduanya berbagi struktur pool yang sama (pool_yes/pool_no), antarmuka taruhan, dan alur klaim. Pasar trustless menggunakan fixture_id dari TxLINE; pasar manual menggunakan fixture_id=0.",
  },
  {
    q: "Dompet apa yang didukung? Bagaimana pengaturannya?",
    a: "FullTime berjalan di Solana Devnet. Dompet yang didukung: Phantom, Solflare, dan Torus (login sosial). Cara pengaturan: (1) Pasang ekstensi browser Phantom, (2) Buka Phantom → Settings → Developer Settings → Testnet Mode → pilih Devnet, (3) Dapatkan SOL gratis dari halaman /faucet atau faucet.solana.com (login GitHub diperlukan), (4) Hubungkan di /app. Program Anchor di-deploy di 58a2h7zogfV5ZgUsfyr1DZ36j1bgcwfCkGvd8fwppy5x di devnet.",
  },
  {
    q: "Bagaimana cara mendapatkan SOL tes?",
    a: "Kunjungi halaman Faucet (/faucet). Hubungkan dompet Phantom Anda (Devnet) dan klik 'Minta 1 SOL'. Ini memanggil metode Solana JSON-RPC requestAirdrop. Jika terkena rate limit, gunakan faucet.solana.com langsung — masuk dengan GitHub, tempel alamat dompet Anda, selesaikan captcha, dan klaim hingga 5 SOL per permintaan. SOL Devnet tidak memiliki nilai moneter nyata.",
  },
  {
    q: "Apa langkah keamanan yang melindungi kontrak pintar?",
    a: "Tujuh lapis keamanan: (1) Semua aritmatika menggunakan checked_add/sub/mul/div — nol matematika tidak terperiksa. (2) Siklus status pasar ditegakkan ketat (Pending→Open→Closed→Settled/Cancelled), setiap instruksi memvalidasi status saat ini. (3) Batasan hanya-pembuat via Anchor constraint = market.creator == creator.key(). (4) settle_market memverifikasi PDA daily_scores_merkle_roots terhadap ID program TxLINE yang dikenal via findProgramAddressSync. (5) CPI ke validate_stat menggunakan discriminator 8-byte tetap yang cocok dengan Txoracle IDL v1.4.2. (6) Di-deploy via BPFLoaderUpgradeable, pemuat program standar Solana. (7) 15 unit test komprehensif mencakup semua kasus sukses dan error.",
  },
  {
    q: "Bisakah saya membatalkan pasar atau mendapatkan refund?",
    a: "Ya. Pembuat pasar dapat memanggil cancelMarket kapan saja saat status Pending, Open, atau Closed (bukan Settled). Petaruh kemudian memanggil refundBet yang: (a) memverifikasi pasar Dibatalkan, (b) mengurangi jumlah taruhan dari pool terkait (pool_yes atau pool_no), (c) mentransfer SOL dari PDA pasar kembali ke petaruh, (d) menutup otomatis akun taruhan via batasan close=bettor Anchor, mengklaim kembali lamports sewa. Tidak ada dana yang terkunci permanen.",
  },
  {
    q: "Apa bedanya FullTime dengan Polymarket atau Augur?",
    a: "Polymarket berjalan di Polygon dan bergantung pada UMA's Optimistic Oracle — sistem penyelesaian sengketa manusia di mana hasil dipilih. Augur v2 menggunakan model berbasis sengketa serupa dengan pemegang token REP. Pembeda utama FullTime: penyelesaian murni matematis. Merkle proof TxLINE diverifikasi on-chain via CPI — entah valid atau tidak. Tanpa jendela sengketa, tanpa periode tantangan, tanpa voting. Selain itu, relay berbasis SSE mencapai latensi penyelesaian di bawah 1 detik versus menit atau jam pada sistem berbasis sengketa. Untuk pasar manual, pembuat menyelesaikan langsung — trade-off yang memperluas alam semesta prediksi sambil menjaga inti tanpa kepercayaan.",
  },
  {
    q: "Bagaimana cara memverifikasi semuanya on-chain?",
    a: "Semua alamat dapat diverifikasi di Solscan (devnet). Alamat kunci: Program ID 58a2h7zogfV5ZgUsfyr1DZ36j1bgcwfCkGvd8fwppy5x, TxLINE Txoracle 6pW64gN1s2uqjHkn1unFeEjAwJkPGHoppGvS715wyP2J. Setiap PDA pasar diturunkan secara deterministik dari seed [b'market', program_id, creator_pubkey, fixture_id_le]. Setiap PDA taruhan dari [b'bet', market_pubkey, bettor_pubkey]. Setiap transaksi settle_market secara permanen mencatat PDA daily_scores_merkle_roots. Kode sumber lengkap di github.com/yt2025id-lab/fulltime (publik).",
  },
  {
    q: "Apa itu relay service dan arsitektur SSE?",
    a: "Relay service (relay-service/src/) menjembatani umpan real-time TxLINE dengan Solana. Arsitektur: (1) scores-stream.ts terhubung ke TxLINE SSE, mendeteksi perubahan fase (5/10/13=settle, 15/16=cancel) menggunakan AbortController untuk teardown bersih dan backoff eksponensial. (2) proof-fetcher.ts mengambil Merkle proof via 2 panggilan API (statKey=1 home, statKey=2 away). (3) settlement-submitter.ts membangun transaksi dengan 1.4M CU ComputeBudget untuk verifikasi CPI. (4) index.ts mengorkestrasi SSE + polling fallback 60d + sinkronisasi registri pasar. Relay beroperasi permissionless — siapa pun bisa menjalankannya.",
  },
  {
    q: "Apa tech stack dan mengapa pilihan ini?",
    a: "Smart Contract: Anchor v0.30.1 + Rust, di-deploy via BPFLoaderUpgradeable di Solana Devnet. Anchor dipilih karena derive macros (Accounts, program), generasi IDL otomatis, dan pola yang telah teruji. Frontend: React 19 + Vite 8 + TypeScript + Tailwind CSS v4, dengan @solana/wallet-adapter-react (Phantom/Solflare/Torus) dan @coral-xyz/anchor. IDL dimuat saat runtime via fetch('/idl.json'). Framer Motion untuk animasi. Relay Service: Node.js + TypeScript, SSE untuk data TxLINE real-time, @solana/web3.js untuk pengiriman transaksi. Vercel untuk hosting (fulltime-wc.vercel.app). API football-data.org untuk skor langsung, klasemen, dan data gugur.",
  },
];

const fadeIn = {
  initial: { filter: "blur(8px)", opacity: 0, y: 20 },
  animate: { filter: "blur(0px)", opacity: 1, y: 0 },
};

export default function Faq() {
  const { t, lang } = useLang();
  const { connected, publicKey } = useWallet();
  const [open, setOpen] = useState<number | null>(null);

  return (
    <div className="min-h-screen bg-gradient-to-b from-emerald-950 via-zinc-900 to-zinc-950 relative">
      <div className="fixed inset-0 z-0 bg-cover bg-center opacity-[0.04]" style={{ backgroundImage: `url(https://images.unsplash.com/photo-1551958219-acbc608c6377?w=1920&q=80)` }} />

      <nav className="sticky top-0 z-40 border-b border-emerald-500/20 bg-zinc-900/90 backdrop-blur-lg">
        <div className="max-w-7xl mx-auto grid grid-cols-3 items-center px-4 sm:px-6 py-3">
          <Link to="/" className="flex items-center gap-2">
            <span className="text-xl">⚽</span>
            <span className="font-mono font-bold text-white text-lg tracking-tight">Full<span className="text-white/40">Time</span></span>
          </Link>
          <div className="flex items-center justify-center gap-2">
            <Link to="/app" className="rounded-full px-4 py-1.5 text-sm font-mono text-white/50 hover:text-white transition-colors">{t("nav.markets")}</Link>
            <Link to="/matches" className="rounded-full px-4 py-1.5 text-sm font-mono text-white/50 hover:text-white transition-colors">{t("nav.matches")}</Link>
            <Link to="/faq" className="bg-white/15 rounded-full px-4 py-1.5 text-sm font-mono text-white font-medium">{t("nav.faq")}</Link>
            <Link to="/faucet" className="rounded-full px-4 py-1.5 text-sm font-mono text-white/50 hover:text-white transition-colors">{t("nav.faucet")}</Link>
          </div>
          <div className="flex items-center justify-end gap-2">
            <LangToggle />
            {connected ? (
              <WalletDisconnectButton style={{ background: "#262626", color: "#fff", borderRadius: "9999px", padding: "6px 16px", fontSize: "12px", fontFamily: "ui-monospace,monospace", border: "none" }} />
            ) : (
              <WalletModalButton style={{ background: "#171717", color: "#fff", borderRadius: "9999px", padding: "8px 20px", fontSize: "14px", fontFamily: "ui-monospace,monospace", fontWeight: 600, border: "1px solid rgba(255,255,255,0.2)" }} />
            )}
          </div>
        </div>
      </nav>

      <div className="relative z-10 max-w-2xl mx-auto px-4 sm:px-6 py-12">
        <motion.div {...fadeIn} transition={{ duration: 0.6 }}>
          <p className="text-sm font-mono text-amber-400/60 mb-4">{t("faq.subtitle")}</p>
          <h1 className="font-mono font-bold text-white text-5xl md:text-6xl tracking-[-2px] mb-4">
            <span className="text-amber-400/60">{lang === "id" ? "Tanya" : "Frequently Asked"}</span> {lang === "id" ? "Jawab" : "Questions"}
          </h1>
          <p className="font-mono text-sm text-white/40 mb-10">
            {lang === "id" ? "Semua tentang FullTime — pasar prediksi tanpa kepercayaan untuk Piala Dunia 2026 di Solana." : "Everything about FullTime — trustless prediction market for World Cup 2026 on Solana."}
          </p>
        </motion.div>

        <div className="space-y-3">
          {(lang === "id" ? faqID : faqEN).map((item, i) => (
            <motion.div
              key={i}
              initial={{ filter: "blur(5px)", opacity: 0, y: 20 }}
              whileInView={{ filter: "blur(0px)", opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.04 }}
            >
              <div className="group relative w-full overflow-hidden rounded-2xl bg-zinc-800/40 font-sans shadow-2xl border border-zinc-600/20">
                <div className="absolute -top-1/2 left-1/2 h-64 w-64 -translate-x-1/2 rounded-full bg-gradient-to-br from-emerald-500/20 via-amber-500/10 to-transparent blur-3xl transition-all duration-700 group-hover:from-emerald-500/30 group-hover:via-amber-500/20" />
                <div className="relative z-10">
                <div
                  className="p-5 cursor-pointer"
                  onClick={() => setOpen(open === i ? null : i)}
                >
                  <div className="flex items-center justify-between gap-3">
                    <h3 className="font-mono font-bold text-white text-sm flex-1">{item.q}</h3>
                    <span className={`font-mono text-lg shrink-0 transition-transform duration-300 ${open === i ? "rotate-45 text-amber-400" : "text-white/30"}`}>+</span>
                  </div>
                  {open === i && (
                    <motion.p
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: "auto" }}
                      transition={{ duration: 0.3 }}
                      className="mt-4 font-mono text-sm text-white/50 leading-relaxed border-t border-zinc-600/20 pt-4"
                    >
                      {item.a}
                    </motion.p>
                  )}
                </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        <div className="mt-12 text-center">
          <p className="font-mono text-xs text-white/20">
            {t("faq.footer")}
          </p>
        </div>
      </div>

      <footer className="border-t border-amber-500/10 py-6 text-center">
        <p className="font-mono text-[10px] text-white/30">{t("footer.text")}</p>
        <p className="font-mono text-[10px] text-white/20">{t("footer.sub")}</p>
      </footer>
    </div>
  );
}
