import { useState } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import GlowCard from "../components/GlowCard";

const faq = [
  {
    q: "What is FullTime?",
    a: "FullTime is a trustless, on-chain prediction market protocol built on Solana for FIFA World Cup 2026. Developed for the TxODDS × Solana × Superteam Earn Hackathon ($18,000 prize pool, Prediction Markets & Settlement track). Unlike centralized platforms where a human operator clicks 'resolve', FullTime eliminates trust entirely: settlement outcomes are verified cryptographically via Merkle proofs generated by TxLINE (TxODDS' oracle network) and executed on-chain through Cross-Program Invocation (CPI). Either the proof checks out, or the transaction reverts. No middleman, no admin key, no dispute window.",
  },
  {
    q: "How does trustless settlement work?",
    a: "When a match concludes, TxLINE produces a cryptographic Merkle tree containing all verified match statistics for that day. The relay service detects this via SSE (Server-Sent Events), fetches Merkle proofs from /api/scores/stat-validation, and submits a settle_market transaction. The on-chain program performs CPI into TxLINE's validate_stat instruction which verifies: (1) the stat→fixture Merkle proof path, (2) the fixture→daily root proof path, (3) the daily_scores_roots PDA is authentic. If all three checks pass, the winner is derived: home_goals > away_goals → YES, otherwise → NO. From final whistle to on-chain confirmation: under 1 second.",
  },
  {
    q: "How does YES/NO and payout math work?",
    a: "FullTime uses binary YES/NO markets with parimutuel pooling. All bets on the losing side are distributed proportionally to winners. Payout formula: gross = your_bet × (total_pool / winning_pool). Protocol fee is 200 bps (2%), calculated as fee = gross × 200 / 10000. Net payout = gross - fee. If you bet 0.1 SOL on YES with a 0.3 SOL winning pool and 0.5 SOL total pool, you receive approximately 0.163 SOL — your stake plus your share of the NO pool. All arithmetic uses Anchor's checked_add/sub/mul/div to prevent overflow vulnerabilities.",
  },
  {
    q: "What are the two market types?",
    a: "Trustless Markets (isTrustless=true): tied to TxLINE fixture IDs, auto-settled via Merkle proof CPI when the match ends, no human intervention needed. Manual Markets (isTrustless=false): created for any YES/NO question, the market creator calls resolve_market(outcome) to settle. Both share the same pool structure (pool_yes/pool_no), bet interface, and claim flow. Trustless markets use fixture_id from TxLINE; manual markets use fixture_id=0.",
  },
  {
    q: "What wallets are supported? How do I set up?",
    a: "FullTime runs on Solana Devnet. Supported wallets: Phantom, Solflare, and Torus (social login). To set up: (1) Install Phantom browser extension, (2) Open Phantom → Settings → Developer Settings → Testnet Mode → select Devnet, (3) Get free SOL from the /faucet page or faucet.solana.com (GitHub login required), (4) Connect on /app. The Anchor program is deployed at 58a2h7zogfV5ZgUsfyr1DZ36j1bgcwfCkGvd8fwppy5x on devnet.",
  },
  {
    q: "How do I get test SOL?",
    a: "Visit the built-in Faucet page (/faucet). Connect your Phantom wallet (Devnet) and click 'Request 1 SOL'. This calls the Solana JSON-RPC requestAirdrop method. If rate-limited, use faucet.solana.com directly — sign in with GitHub, paste your wallet address, complete captcha, and claim up to 5 SOL per request. Devnet SOL has no real monetary value.",
  },
  {
    q: "What security measures protect the smart contract?",
    a: "Seven layers of security: (1) All arithmetic uses checked_add/sub/mul/div — zero unchecked math. (2) Market status lifecycle is strictly enforced (Pending→Open→Closed→Settled/Cancelled), every instruction validates current state. (3) Creator-only constraints via Anchor's constraint = market.creator == creator.key(). (4) settle_market verifies daily_scores_merkle_roots PDA against known TxLINE program ID via findProgramAddressSync. (5) CPI to validate_stat uses a fixed 8-byte discriminator matching Txoracle IDL v1.4.2. (6) Deployed via BPFLoaderUpgradeable, Solana's standard program loader. (7) 15 comprehensive unit tests covering all happy paths and error cases.",
  },
  {
    q: "Can I cancel a market or get a refund?",
    a: "Yes. Market creator can call cancelMarket at any time while status is Pending, Open, or Closed (not Settled). Bettors then call refundBet which: (a) verifies market is Cancelled, (b) deducts bet amount from the corresponding pool (pool_yes or pool_no), (c) transfers SOL from the market PDA back to the bettor, (d) auto-closes the bet account via Anchor's close=bettor constraint, reclaiming rent-exempt lamports. No funds are permanently locked.",
  },
  {
    q: "How is FullTime different from Polymarket or Augur?",
    a: "Polymarket runs on Polygon and relies on UMA's Optimistic Oracle — a human dispute resolution system where outcomes are voted on. Augur v2 uses a similar dispute-based model with REP token holders. FullTime's core differentiator: settlement is purely mathematical. The TxLINE Merkle proof is verified on-chain via CPI — either it validates or it doesn't. No dispute window, no challenge period, no voting. Additionally, SSE-based relay achieves sub-1-second settlement latency versus minutes or hours on dispute-based systems. For manual markets, the creator resolves directly — a trade-off that expands the universe of possible predictions while keeping the trustless core intact.",
  },
  {
    q: "How do I verify everything on-chain?",
    a: "All addresses are verifiable on Solscan (devnet). Key addresses: Program ID 58a2h7zogfV5ZgUsfyr1DZ36j1bgcwfCkGvd8fwppy5x, TxLINE Txoracle 6pW64gN1s2uqjHkn1unFeEjAwJkPGHoppGvS715wyP2J. Every market PDA is deterministically derived from seeds [b'market', program_id, creator_pubkey, fixture_id_le]. Every bet PDA from [b'bet', market_pubkey, bettor_pubkey]. Every settle_market transaction permanently records the daily_scores_merkle_roots PDA. Full source code at github.com/yt2025id-lab/fulltime (public).",
  },
  {
    q: "What is the relay service and SSE architecture?",
    a: "The relay service (relay-service/src/) bridges TxLINE's real-time feed with Solana. Architecture: (1) scores-stream.ts connects to TxLINE SSE, detects phase changes (5/10/13=settle, 15/16=cancel) using AbortController for clean teardown and exponential backoff. (2) proof-fetcher.ts fetches Merkle proofs via 2 API calls (statKey=1 home, statKey=2 away). (3) settlement-submitter.ts builds transactions with 1.4M CU ComputeBudget for CPI verification. (4) index.ts orchestrates SSE + 60s polling fallback + market registry sync. The relay operates permissionlessly — anyone can run it.",
  },
  {
    q: "What's the tech stack and why these choices?",
    a: "Smart Contract: Anchor v0.30.1 + Rust, deployed via BPFLoaderUpgradeable on Solana Devnet. Anchor chosen for derive macros (Accounts, program), automatic IDL generation, and battle-tested patterns. Frontend: React 19 + Vite 8 + TypeScript + Tailwind CSS v4, with @solana/wallet-adapter-react (Phantom/Solflare/Torus) and @coral-xyz/anchor. IDL loaded at runtime via fetch('/idl.json'). Framer Motion for animations. Relay Service: Node.js + TypeScript, SSE for real-time TxLINE data, @solana/web3.js for transaction submission. Vercel for hosting (fulltime-wc.vercel.app). football-data.org API for live scores, standings, and knockout data.",
  },
];

const fadeIn = {
  initial: { filter: "blur(8px)", opacity: 0, y: 20 },
  animate: { filter: "blur(0px)", opacity: 1, y: 0 },
};

export default function Faq() {
  const [open, setOpen] = useState<number | null>(null);

  return (
    <div className="min-h-screen bg-black relative">
      <div className="fixed inset-0 z-0 bg-cover bg-center" style={{ backgroundImage: "url(https://images.unsplash.com/photo-1551958219-acbc608c6377?w=1920&q=80)" }}>
        <div className="absolute inset-0 bg-black/85 backdrop-blur-[2px]" />
      </div>

      <nav className="sticky top-0 z-40 border-b border-red-800/30 bg-[#c0392b]/95 backdrop-blur-lg">
        <div className="max-w-7xl mx-auto grid grid-cols-3 items-center px-4 sm:px-6 py-3">
          <div className="flex items-center gap-4">
            <Link to="/app" className="text-sm text-white/70 hover:text-white font-mono transition-colors">&larr; Back</Link>
            <span className="text-lg">⚽</span>
            <span className="font-mono font-bold text-white text-lg">Full<span className="text-white/40">Time</span></span>
          </div>
          <div className="flex items-center justify-center gap-2">
            <Link to="/app" className="rounded-full px-4 py-1.5 text-sm font-mono text-white/50 hover:text-white transition-colors">Markets</Link>
            <Link to="/matches" className="rounded-full px-4 py-1.5 text-sm font-mono text-white/50 hover:text-white transition-colors">Matches</Link>
            <Link to="/faq" className="bg-white/15 rounded-full px-4 py-1.5 text-sm font-mono text-white font-medium">FAQ</Link>
          </div>
          <div />
        </div>
      </nav>

      <div className="relative z-10 max-w-2xl mx-auto px-4 sm:px-6 py-12">
        <motion.div {...fadeIn} transition={{ duration: 0.6 }}>
          <p className="text-sm font-mono text-red-300/60 mb-4">// FAQ</p>
          <h1 className="font-mono font-bold text-white text-5xl md:text-6xl tracking-[-2px] mb-4">
            Frequently Asked <span className="text-red-300/60">Questions</span>
          </h1>
          <p className="font-mono text-sm text-white/40 mb-10">
            Everything about FullTime — trustless prediction market for World Cup 2026 on Solana.
          </p>
        </motion.div>

        <div className="space-y-3">
          {faq.map((item, i) => (
            <motion.div
              key={i}
              initial={{ filter: "blur(5px)", opacity: 0, y: 20 }}
              whileInView={{ filter: "blur(0px)", opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.04 }}
            >
              <GlowCard className="!min-h-0">
                <div
                  className="p-5 cursor-pointer"
                  onClick={() => setOpen(open === i ? null : i)}
                >
                  <div className="flex items-center justify-between gap-3">
                    <h3 className="font-mono font-bold text-white text-sm flex-1">{item.q}</h3>
                    <span className={`font-mono text-lg shrink-0 transition-transform duration-300 ${open === i ? "rotate-45 text-red-400" : "text-white/30"}`}>+</span>
                  </div>
                  {open === i && (
                    <motion.p
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: "auto" }}
                      transition={{ duration: 0.3 }}
                      className="mt-4 font-mono text-sm text-white/50 leading-relaxed border-t border-white/[0.06] pt-4"
                    >
                      {item.a}
                    </motion.p>
                  )}
                </div>
              </GlowCard>
            </motion.div>
          ))}
        </div>

        <div className="mt-12 text-center">
          <p className="font-mono text-xs text-white/20">
            Built for TxODDS x Solana x Superteam Earn Hackathon · July 2026
          </p>
        </div>
      </div>
    </div>
  );
}
