import { Link } from "react-router-dom";
import Marquee from "../components/Marquee";
const M1 = ["⚽ 🇦🇷 Argentina","⚽ 🇧🇷 Brazil","⚽ 🇺🇾 Uruguay","⚽ 🇨🇴 Colombia","⚽ 🇪🇨 Ecuador","⚽ 🇵🇾 Paraguay","⚽ 🇨🇱 Chile","⚽ 🇵🇪 Peru"];
const M2 = ["⚽ 🇫🇷 France","⚽ 🇪🇸 Spain","⚽ 🏴󠁧󠁢󠁥󠁮󠁧󠁿 England","⚽ 🇩🇪 Germany","⚽ 🇵🇹 Portugal","⚽ 🇳🇱 Netherlands","⚽ 🇧🇪 Belgium","⚽ 🇮🇹 Italy"];
const M3 = ["⚽ 🇭🇷 Croatia","⚽ 🇨🇭 Switzerland","⚽ 🇳🇴 Norway","⚽ 🇦🇹 Austria","⚽ 🇸🇪 Sweden","⚽ 🇩🇰 Denmark","⚽ 🇵🇱 Poland","⚽ 🇹🇷 Turkey"];
const M4 = ["⚽ 🇯🇵 Japan","⚽ 🇰🇷 South Korea","⚽ 🇸🇦 Saudi Arabia","⚽ 🇦🇺 Australia","⚽ 🇮🇷 Iran","⚽ 🇮🇶 Iraq","⚽ 🇺🇿 Uzbekistan","⚽ 🇯🇴 Jordan"];
const M5 = ["⚽ 🇲🇦 Morocco","⚽ 🇸🇳 Senegal","⚽ 🇹🇳 Tunisia","⚽ 🇩🇿 Algeria","⚽ 🇪🇬 Egypt","⚽ 🇨🇮 Côte d'Ivoire","⚽ 🇬🇭 Ghana","⚽ 🇨🇲 Cameroon"];
const M6 = ["⚽ 🇺🇸 USA","⚽ 🇲🇽 Mexico","⚽ 🇨🇦 Canada","⚽ 🇵🇦 Panama","⚽ 🇯🇲 Jamaica","⚽ 🇨🇷 Costa Rica","⚽ 🇳🇿 New Zealand","⚽ 🇿🇦 South Africa"];
export default function Landing() {
  return (<div className="min-h-screen bg-[#0a0a0f] text-white overflow-hidden">
    <nav className="fixed top-0 left-0 right-0 z-50 border-b border-white/10 bg-[#0a0a0f]/80 backdrop-blur-xl"><div className="max-w-7xl mx-auto px-6 h-16 flex items-center"><img src="/logo fulltime.png" alt="FullTime" className="h-8 w-auto" /></div></nav>
    <section className="relative pt-32 pb-20 px-6 border-b border-white/10 overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-b from-[#FF1493]/10 via-transparent to-transparent" />
      <div className="absolute top-20 right-0 w-96 h-96 bg-[#FF1493]/5 rounded-full blur-3xl" />
      <div className="absolute bottom-0 left-0 w-64 h-64 bg-[#FFD700]/5 rounded-full blur-3xl" />
      <div className="max-w-5xl mx-auto relative z-10 text-center">
        <img src="/logo fulltime.png" alt="FullTime" className="h-16 md:h-24 mx-auto mb-8" />
        <h1 className="text-5xl md:text-8xl font-black leading-none mb-6"><span className="block bg-gradient-to-r from-white via-white to-[#FF1493] bg-clip-text text-transparent">CRYPTO SETTLES.</span><span className="block text-2xl md:text-3xl mt-4 text-white/50 font-bold">NO REFEREE NEEDED.</span></h1>
        <p className="text-lg text-white/40 max-w-2xl mx-auto mb-10">Prediction market on-chain untuk World Cup 2026. Settlement otomatis diverifikasi kriptografis via Merkle proofs — tanpa admin, tanpa tombol resolve, tanpa kepercayaan.</p>
        <div className="flex gap-4 justify-center flex-wrap">
          <Link to="/markets" className="group relative bg-white text-black text-lg font-black px-8 py-4 rounded-2xl overflow-hidden hover:bg-[#FF1493] hover:text-white transition-all duration-500">EXPLORE MARKETS</Link>
          <Link to="/admin" className="group relative bg-white/10 text-white text-lg font-black px-8 py-4 rounded-2xl overflow-hidden border border-white/20 hover:bg-white hover:text-black transition-all duration-500">CREATE MARKET</Link>
        </div>
      </div>
    </section>
    <Marquee countries={M1} />
    <section className="py-24 px-6 border-b border-white/10 relative overflow-hidden"><div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#FF1493]/3 to-transparent" /><div className="max-w-5xl mx-auto relative z-10 grid grid-cols-1 md:grid-cols-3 gap-6">{[{t:"TRUSTLESS",e:"🔐",d:"Settlement diverifikasi via Merkle proof on-chain — tidak ada pihak yang harus dipercaya."},{t:"AUTOMATIC",e:"⚡",d:"Peluit akhir → relay service mendeteksi → settle dalam hitungan detik via SSE stream."},{t:"AUDITABLE",e:"🔍",d:"Setiap settlement meninggalkan jejak permanen di Solana, diverifikasi siapa saja."}].map((f,i)=>(<div key={f.t} className="group bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-8 hover:bg-white/10 hover:border-[#FF1493]/30 transition-all duration-500"><div className="text-4xl mb-4">{f.e}</div><h3 className="text-2xl font-black mb-3">{f.t}</h3><p className="text-white/40 leading-relaxed">{f.d}</p></div>))}</div></section>
    <Marquee countries={M2} reverse />
    <section className="py-24 px-6 border-b border-white/10"><div className="max-w-5xl mx-auto"><h2 className="text-4xl md:text-5xl font-black text-center mb-4">HOW <span className="bg-gradient-to-r from-[#FFD700] to-[#FF1493] bg-clip-text text-transparent">IT WORKS</span></h2><p className="text-center text-white/40 text-lg mb-16">From whistle to wallet — fully automated, cryptographically verified</p><div className="grid grid-cols-1 md:grid-cols-5 gap-4">{[{s:"1",i:"🏟️",t:"KICKOFF",d:"Match dimulai. Bettors pasang taruhan HOME/DRAW/AWAY"},{s:"2",i:"⏱️",t:"FULL TIME",d:"TxLINE mendeteksi phase F melalui live data feed"},{s:"3",i:"🔗",t:"MERKLE PROOF",d:"TxLINE generates cryptographic proof ke on-chain"},{s:"4",i:"⛓️",t:"CPI VERIFY",d:"FullTime contract verifies proof via CPI ke TxLINE"},{s:"5",i:"💰",t:"SETTLE",d:"Market auto-settled. Pemenang klaim payout."}].map((w)=>(<div key={w.s} className="group bg-white/5 border border-white/10 rounded-2xl p-6 text-center hover:border-[#FFD700]/30 transition-all duration-500"><div className="text-3xl mb-2">{w.i}</div><div className="w-8 h-8 rounded-full bg-gradient-to-r from-[#FFD700] to-[#FF1493] flex items-center justify-center mx-auto mb-2 font-black text-sm text-black">{w.s}</div><h4 className="font-black text-sm mb-1">{w.t}</h4><p className="text-xs text-white/30">{w.d}</p></div>))}</div></div></section>
    <Marquee countries={M3} />
    <section className="py-24 px-6 border-b border-white/10"><div className="max-w-4xl mx-auto"><h2 className="text-4xl md:text-5xl font-black text-center mb-4">WHY <span className="bg-gradient-to-r from-[#FF1493] to-[#FFD700] bg-clip-text text-transparent">FULLTIME</span> WINS</h2><p className="text-center text-white/40 text-lg mb-16">No contest.</p><div className="border border-white/10 rounded-2xl overflow-hidden backdrop-blur-sm"><table className="w-full text-left"><thead><tr className="bg-white/5"><th className="p-4 font-black text-sm">FEATURE</th><th className="p-4 font-black text-sm border-l border-white/10 bg-[#FF1493]/10 text-[#FF1493]">FULLTIME</th><th className="p-4 font-black text-sm border-l border-white/10">TRADITIONAL</th></tr></thead><tbody className="divide-y divide-white/10">{[["Settlement","Auto < 1 detik","Manual admin klik"],["Verifikasi","Merkle proof on-chain","Trust-based"],["Audit Trail","Permanent di Solana","Tidak ada"],["Data Source","TxLINE verified","Manual/Web scraping"],["Censorship","Permissionless","Admin kontrol"],["Latency","SSE real-time","Polling 2-5 menit"]].map(([f,ft,tr],i)=>(<tr key={f} className={i%2===0?"bg-white/[0.02]":""}><td className="p-4 font-bold text-sm">{f}</td><td className="p-4 text-sm bg-[#FF1493]/5 border-l border-white/10 text-green-400 font-bold">{ft}</td><td className="p-4 text-sm border-l border-white/10 text-red-400">{tr}</td></tr>))}</tbody></table></div></div></section>
    <Marquee countries={M4} reverse />
    <Marquee countries={M5} />
    <section className="py-24 px-6 relative overflow-hidden"><div className="absolute inset-0 bg-gradient-to-t from-[#FF1493]/10 via-transparent to-transparent" /><div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[600px] bg-[#FF1493]/10 rounded-full blur-3xl" /><div className="max-w-3xl mx-auto relative z-10 text-center"><h2 className="text-4xl md:text-5xl font-black mb-6">READY TO <span className="bg-gradient-to-r from-[#FFD700] to-[#FF1493] bg-clip-text text-transparent">SETTLE</span>?</h2><p className="text-xl text-white/40 mb-10">World Cup 2026 sedang berlangsung. Buat market, pasang taruhan, biarkan blockchain bekerja.</p><div className="flex gap-4 justify-center"><Link to="/markets" className="bg-white text-black text-lg font-black px-8 py-4 rounded-2xl hover:bg-[#FF1493] hover:text-white transition-all duration-500">EXPLORE MARKETS</Link><Link to="/admin" className="bg-white/10 text-white text-lg font-black px-8 py-4 rounded-2xl border border-white/20 hover:bg-white hover:text-black transition-all duration-500">CREATE MARKET</Link></div></div></section>
    <Marquee countries={M6} reverse />
    <footer className="py-8 border-t border-white/10 text-center"><p className="text-sm text-white/20">FullTime — Built on Solana. Powered by TxLINE. World Cup 2026.</p><p className="text-xs text-white/10 mt-1">TxODDS x Solana x Superteam Earn Hackathon · Prediction Markets & Settlement</p></footer>
  </div>);
}